#!/bin/sh

echo "<span foreground='#fff' size='large'>  </span><span foreground='#fff'>$(upower -i $(upower -e | grep 'BAT') | grep -E "percentage" | awk '{print toupper($2)}' | sed 's/.$//') $(upower -i $(upower -e | grep 'BAT') | grep -E "state" | awk '{print toupper($2)}'|cut -c 1) \\\</span>"
